### ISSUE TITLE
Trackside camera doesn't work

### ISSUE THREAD

**Issue by rickvanoverbeek** [ac-custom-shaders-patch/acc-obs-plugin#1]
When I add the Trackside camera, it doesn't provide me with an image. It's just black. The regular view in cockpit works though.

**Comment by turbasosimracing** [comment]
If you are rendering i triple screen i think is not supported yet

**Comment by nemaides** [comment]
> When I add the Trackside camera, it doesn't provide me with an image. It's just black. The regular view in cockpit works though.

Funny i have the opposite issue, every other camera works besides Clean View and Include HUD.

Edit: i fixed my issue, i was running 0.2.1, downgraded to 0.2.0 and it worked for me again.

**Comment by mjcarter** [comment]
@nemaides Have got the same issue where all cams work except Clean View and include HUD. Clean View is just a black screen and Include HUD seems to show the loading screen still

**Comment by AcidicVoid** [comment]
@mjcarter Were you able to fix the issue? I have the same problem and can't find any solution.

**Comment by mjcarter** [comment]
No still not working for me, I didn't try downgrading CSP version though.

**Comment by AcidicVoid** [comment]
@mjcarter It worked for me after downgrading to 0.2.1-preview
I wasn't able to find a different solution

**Comment by mjcarter** [comment]
I'm running 0.23-preview, this not a big deal enough for me to consider downgrading CSP version so happy to put up with it until there's another solution. It's amazing this software is even possible (without a big impact on FPS), seems like some kind of magic
